### ISSUE TITLE
Uploaded a PNG file, got a "something is wrong we're looking at it"

### ISSUE THREAD

**Issue by vielmetti** [DOE-NEPA/NEPAnode#1]
The file in question is a DTE Energy outage map

**Comment by JJediny** [comment]
http://nepanode.anl.gov is for uploading Geospatial data (Shapefiles/Geotiffs) our MapWarper site - http://warp.nepanode.anl.gov is made for uploading/georeferencing map images... ?

**Comment by vielmetti** [comment]
I have something that looks like it works here 

http://warp.nepanode.anl.gov/maps/591

**Comment by vielmetti** [comment]
Working for me now, closing this.
